### ISSUE TITLE
startup crash exit code 1

### ISSUE THREAD

**Issue by kaairu** [TathanDev/GiantsOverhaul#1]
https://paste.modularity.gg/paste?content=https://cdn.discordapp.com/attachments/1101396706861531157/1165718999426932769/latest.log?ex=6547df6b&is=65356a6b&hm=faa16ed71b60c2795067acfde225310934f1733a38cdf8b077c782841592a5da&&raw=false

**Comment by TathanDev** [comment]
Sorry i didn't see the issues !
But yes the bug is fixed now
